vpx-meninblack
LegendsUnchained/vpx-standalone-alp4k pull request #19
Opened 2024-07-24 16:13 UTC by Kaoticbpr

adding vpx-meninblack

Please ensure your PR includes the following:

- README.md
- launcher.png
- launcher.xml
- pinmame/cfg, pinmame/ini, pinmame/nvram, pinmame/roms folders. If they are empty, create a .gitkeep file to ensure the folders get created in the repo.
- any game specific ini or vbs files named exactly the same as the publicly available files from either VPForums or VPUniverse

Please ensure your PR **DOES NOT** include any of the following:

- VPX files
- ROMs
- PUP Media files
- Any sort of licensing text that goes against the licensing of this repository

By submitting this PR, you are agreeing that any artwork submitted is your own, or you have the legal right to distribute such artwork.

2024-07-25 04:35 UTC, n-i-x requested changes
Missing pinmame folder structure with .gitkeep folders and updates to main README.md table directory.

2024-07-25 04:35 UTC, n-i-x commented on external/vpx-meninblack/VPReg.ini
Set all scores to 100000 and use the following initials in order:

JSM
CTH
NIX
VPX

2024-07-25 04:35 UTC, n-i-x commented on external/vpx-meninblack/README.md
> +- Download the table and directb2s versions listed above and copy them into this folder
Missing witty instruction

2024-07-27 04:28 UTC, n-i-x commented on external/vpx-rctycn/rollercoastertycoontablepreview.jpg
delete this file

2024-07-27 04:28 UTC, n-i-x commented on external/vpx-rctycn/pinmame/roms/rctycn.zip
do not check roms in... not sure why the gitignore didn't catch it

2024-07-27 04:30 UTC, Kaoticbpr commented on external/vpx-rctycn/pinmame/roms/rctycn.zip
completed

2024-07-27 04:30 UTC, Kaoticbpr commented on external/vpx-rctycn/rollercoastertycoontablepreview.jpg
completed

2024-07-30 20:56 UTC, n-i-x approved these changes

2024-07-30 20:57 UTC, merged