Adding caching in Python dependencies, turn off debugging (#15)
LegendsUnchained/vpx-standalone-alp4k pull request #412
Opened 2024-09-05 23:53 UTC by tschules17

- Adding caching for python dependencies via requirements.txt file
- Removing some debugging detail from python script

2024-09-06 16:42 UTC, n-i-x requested changes

2024-09-06 16:42 UTC, n-i-x commented on .github/workflows/scripts/generate_yml_files.py
> +    yml_file_path = project_directory + "/.github/workflows/temp_yml/" + dir +  '.yml'
this has to be outside of the workflows directory due to permissions... change it to /.wizard/yaml

2024-09-06 16:42 UTC, n-i-x commented on .github/workflows/scripts/generate_yml_files.py
> +    yml_text += get_earliest_commit_owner(project_directory, folder_path)
change the folder_path to use the table xml so we get the actual owner

2024-09-07 15:41 UTC, tschules17 commented
@n-i-x  - the changes are in.  

I thought I had the folder path in there, I think my fork is somehow in a dirty state.  I'll do a reset after this PR gets merged.

2024-09-07 15:43 UTC, n-i-x approved these changes

2024-09-07 15:43 UTC, merged